# Spring DataSource

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    platform: postgres
    url: jdbc:postgresql://localhost:5432/security
    username: postgres
    password: haeni1002

# JPA
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update


# JWT
jwt:
  header: Authorization
  secretKey: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400
