# Spring DataSource

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/security?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: postgres
    password: gosl951

  # JPA
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      platform: postgres

# JWT
jwt:
  header: Authorization
  secretKey: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400
